CREATE TABLE MEMBERS(
    MEMBER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(50)UNIQUE NOT NULL, 
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    F_NAME VARCHAR(50) NOT NULL,
    L_NAME VARCHAR(50) NOT NULL,
    PHONE_NUM VARCHAR(20) NOT NULL,
    CARD_NUMBER VARCHAR(20) NOT NULL

);

CREATE TABLE FINANCIAL_TRANSACTIONS(
FINANCIAL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
MEMBER_ID INTEGER NOT NULL,
DATE DATE NOT NULL, 
AMOUNT VARACHAR(20) NOT NULL,
FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE TABLE RESERVATIONS(
RESERVATION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
MEMBER_ID INTEGER NOT NULL,
DATE DATE NOT NULL,
TRANS_TYPE TEXT CHECK (TRANS_TYPE IN('BOOK', 'EDIT', 'CANCEL')) NOT NULL,
FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)

);

CREATE TABLE ADMIN(
ADMIN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
UDERNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
F_NAME VARCHAR(50) NOT NULL,
L_NAME VARCHAR(50) NOT NULL,
PHONE_NUM VARCHAR(20) NOT NULL


);

